<?php

namespace Nerd;

/**
 * Do not edit this file. If you need to do any framework bootstrapping you should
 * do it in the bootstrap.php file that lives within the application directory.
 */

!defined('DS') and define('DS', DIRECTORY_SEPARATOR);
define('Nerd\LIBRARY_PATH', dirname(dirname(__DIR__)));
define('Nerd\VENDOR_PATH',  dirname(\Nerd\LIBRARY_PATH).DS.'vendor');
define('Nerd\DOCROOT',      dirname(\Nerd\LIBRARY_PATH).DS.'public');
define('Nerd\APPLICATION_NS', 'nerd');

/**
 * Require base test case
 */
include join(DS, [\Nerd\LIBRARY_PATH, 'nerd', 'tests', 'testcase.php']);

/**
 * Get and register the Nerd autoloader.
 */
include join(DS, [\Nerd\LIBRARY_PATH, 'nerd', 'Nerd', 'autoloader.php']);

(new \Nerd\Autoloader)->register(true);
